Display_Timer
animusdev/Old-World-Blues pull request #103
Opened 2018-01-26 13:45 UTC by bombanyTI

2018-01-26 16:36 UTC, TermService requested changes

2018-01-26 16:36 UTC, TermService commented on code/game/objects/items/weapons/grenades/grenade.dm
> +	..()
верни . = ..()

2018-01-26 16:36 UTC, TermService commented on code/modules/client/preference_setup/loadout/head.dm
> +/datum/gear/head/witchhat
ну просил же, не наливать в пулл сразу несколько обнов

2018-01-26 18:00 UTC, bombanyTI commented on code/modules/client/preference_setup/loadout/head.dm
> +/datum/gear/head/witchhat
Путаюсь в кнопках, извините....

2018-01-27 20:51 UTC, TermService commented
сэр у вас чет полетело, закрываю на ремонт

2018-01-27 20:51 UTC, closed without merging