Еще немного абилок конокрадов с поляриса
animusdev/Old-World-Blues pull request #22
Opened 2017-12-26 18:29 UTC by ZerlGray

И бекдоров конечно же.
На локалке проверял вот прям это. Работает. Но на всякий случай можете проверить еще раз.

2017-12-26 18:37 UTC, ZerlGray commented
Был перенес код армблейда в отдельный файл так же.

2017-12-26 18:38 UTC, TermService commented
Вы не прошли проверку Трэвиса, пожалуйста пройдите проверку, спасибо

2017-12-26 18:46 UTC, NazarFogmann commented
>code/game/gamemodes/changeling/modularchangling.dm:122:error: /mob/proc/changeling_armblade: undefined type path

Ты компилишь хоть перед тем как заливать?

2017-12-26 18:47 UTC, TermService commented
Зачем? И так сойдет, блубей же

2017-12-26 19:03 UTC, ZerlGray commented
Естественно компилю. При компиле ноль ошибок. Да ты просто сам возьми да зайди в изменения файлов. Увидишь что /mob/proc/changeling_armblade существует в файле Powers. Это та часть, которую я вообще практически не менял. Я просто перенес это в отдельный файл.

2017-12-26 19:58 UTC, ZerlGray commented
Оно работаит!111

2017-12-26 20:02 UTC, TermService requested changes
Небольшие изменения

2017-12-26 20:02 UTC, TermService commented on code/game/gamemodes/changeling/HelpCode.dm
> +///mob/living/proc/set_m_intent(var/intent)
пустой код лучше удалить

2017-12-26 20:02 UTC, TermService commented on code/game/gamemodes/changeling/Infecting.dm
> +///proc/infect_mob(var/mob/living/carbon/M, var/datum/disease2/disease/D)
и тут

2017-12-26 20:02 UTC, TermService commented on code/game/gamemodes/changeling/Powers.dm
> +		loc << "<span class='notice'>We shape our finger to fit inside electronics, and are ready to force them open.</span>"
такс, такс, что тут у нас? используй леталовские SPAN_NOTE

2017-12-26 20:02 UTC, TermService commented on code/game/gamemodes/changeling/Powers.dm
> +	to_chat(user, "<span class='notice'>We discreetly shape our finger back to a less suspicious form.</span>")
вот так пожалуйста
user << SPAN_NOTE("We discreetly shape our finger back to a less suspicious form.")

2017-12-26 20:02 UTC, TermService commented on code/game/gamemodes/changeling/Powers.dm
> +		H << "<span class='notice'>We vanish from sight, and will remain hidden, so long as we move carefully.</span>"
и тут

2017-12-26 20:03 UTC, ZerlGray commented on code/game/gamemodes/changeling/Powers.dm
> +		loc << "<span class='notice'>We shape our finger to fit inside electronics, and are ready to force them open.</span>"
DA TI ISDEVAYESHSYA!

2017-12-27 06:44 UTC, ZerlGray commented
Готово, чертов тиран.

2017-12-27 07:56 UTC, TermService requested changes
и чейнджлог пожалуйста

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/HelpCode.dm
> +			to_chat(src, "<span class='warning'>You lack the power interact with mechanical constructs.</span>")
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/Infecting.dm
> +		to_chat(src, "<span class='warning'>No suitable targets.</span>")
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/Powers.dm
> +		src << "<span class='warning'>We may only use this power while in humanoid form.</span>"
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/generic_equip_procs.dm
> +		src << "<span class='warning'>We require nothing to be on our head, and we cannot wear any external suits, or shoes.</span>"
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/generic_equip_procs.dm
> +		"<span class='warning'>We cast off our [M.wear_suit.name]</span>",
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/generic_equip_procs.dm
> +			visible_message("<span class='warning'>[src] pulls on their clothes, peeling it off along with parts of their skin attached!</span>",
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/generic_equip_procs.dm
> +		to_chat(M, "<span class='danger'>Your hands are full.</span>")
this^

2017-12-27 07:56 UTC, TermService commented on code/game/gamemodes/changeling/generic_equip_procs.dm
> +/*	var/mob/living/M = holder.wearer
Don't use - remove it

2017-12-27 10:02 UTC, ZerlGray commented on code/game/gamemodes/changeling/HelpCode.dm
> +			to_chat(src, "<span class='warning'>You lack the power interact with mechanical constructs.</span>")
span class='warning'
SPAN_NOTE ="<span class='notice'>
А теперь подумай еще раз.

2017-12-27 10:16 UTC, TermService commented on code/game/gamemodes/changeling/HelpCode.dm
> +			to_chat(src, "<span class='warning'>You lack the power interact with mechanical constructs.</span>")
в данном случае необходимо заменить на SPAN_WARN()

2017-12-27 10:19 UTC, ZerlGray commented on code/game/gamemodes/changeling/HelpCode.dm
> +			to_chat(src, "<span class='warning'>You lack the power interact with mechanical constructs.</span>")
В коде генок не было ни одной замены warning-а на SPAN_WARN, вероятно в этом была какая то причина, раз летал не заменил это.

2017-12-27 16:14 UTC, TermService approved these changes

2017-12-27 16:19 UTC, TermService commented on baystation12.dme
> -// DM Environment file for baystation12.dme.
Не знаю почему оно тут решило, что есть изменения. Вроде все ок, но заметочку оставлю.

2017-12-27 16:21 UTC, merged